apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmitter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transmitter
  template:
    metadata:
      labels:
        app: transmitter
    spec:
      containers:
      - name: transmitter
        image: transmitter-image:tag  # Update to local image
